### ISSUE TITLE
Fix Data ID Values

### ISSUE THREAD

**Issue by dyeany** [PNHP/COA#31]
@ChristopherTracey there are still SGCN records with missing Data ID values. Also, we need to revamp this to make it unique. I thought that it was unique, but discovered today that one value can appear across multiple records.

**Comment by ChristopherTracey** [comment]
Hmm. Is some of this due to multipart EO or CPPs?

**Comment by ChristopherTracey** [comment]
@dyeany was this fixed in the latest SGCN export?

**Comment by dyeany** [comment]
No. This is still an issue which we should address. It's one on which we will need to work together.



--
David Yeany
Conservation Planning Specialist & Ornithologist
Pennsylvania Natural Heritage Program
Western Pennsylvania Conservancy
800 Waterfront Drive, Pittsburgh, PA 15222
Office: 412-586-2313 Mobile: 814-221-4361


-------- Original message --------
